title: Secure L7 & L4 Ingress Controller for Kubernetes
baseurl: https://voyagermesh.com
languageCode: en-us
assetDir: static
googleAnalytics: UA-62096468-4
disableKinds:
- taxonomy
- taxonomyTerm
params:
  product_key: voyager
  main_menu_dropdown_item: database
  domain_appscode: https://appscode.com
  domain_voyagermesh: https://voyagermesh.com
  domain_stash: https://stash.run
  domain_kubedb: https://kubedb.com
  domain_kubevault: https://kubevault.com
  domain_kubeform: https://kubeform.com
  domain_pharmer: https://pharmer.dev
  domain_kubeci: https://kube.ci
  domain_kubeshield: https://kubeshield.com
  domain_bytebuilders: https://byte.builders
  domain_marketplace: https://marketplace.byte.builders
  search_api_key: 8fd610038d901dd16a111e6f1568343bb969b084a1952dafdcb1545fd8c35e96
  blog_url: https://blog.byte.builders
  slack_url: https://slack.appscode.com
  github_url: https://github.com/appscode
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
  comments:
    enable: true
    giscus:
      repo: bytebuilders/community
      repoId: R_kgDOG-h6rw
      category: Voyager
      categoryId: DIC_kwDOG-h6r84COCF5
      map: title
menu:
  main:
  - name: Documentation
    weight: 20
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: manni
outputs:
  home:
  - HTML
  - JSON
